on:
  push:
    branches:
      - main
      - dev
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: VSCE package
        run: |
          npm install
          npm install -g vsce
          vsce package

      - name: Parse tag string
        if: startsWith(github.ref, 'refs/tags/v')
        id: tag_version
        run: |
          echo "result=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT

      - name: Parse version in package.json
        if: startsWith(github.ref, 'refs/tags/v')
        id: package_version
        run: |
          echo "result=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Check if tag matches to package version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "TAG=${{ steps.tag_version.outputs.result }}"
          echo "PACKAGE=${{ steps.package_version.outputs.result }}"
          if [ "${{ steps.tag_version.outputs.result }}" != "${{ steps.package_version.outputs.result }}" ]; then
            echo "Tag version does not match package.json version"
            exit 1
          fi

      - name: GitHub Releases
        if: startsWith(github.ref, 'refs/tags/v') && steps.tag_version.outputs.result == steps.package_version.outputs.result
        uses: softprops/action-gh-release@v2
        with:
          files: ./vscode-3d-preview-${{ steps.tag_string.outputs.result }}.vsix
          draft: false
          prerelease: false

      - name: Publish to VS Code Marketplace
        if: startsWith(github.ref, 'refs/tags/v') && steps.tag_version.outputs.result == steps.package_version.outputs.result
        run: vsce publish -p ${{ secrets.VSCODE_TOKEN }}
