on:
  push:
    branches:
      - main
      - dev
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: VSCE package
        run: |
          npm install
          npm install -g vsce
          vsce package

      - name: Parse tag string
        id: tag_string
        run: echo "result=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./vscode-3d-preview-${{ steps.tag_string.outputs.result }}.vsix
          draft: false
          prerelease: false
